Revert "GH action add ghc-8.0"
Error: cabal: Failed to build documentation for containers-0.6.7 (which is
required by bugzilla-redhat-1.0.1).

This reverts commit 971925ac8ff7eae95e99227a35a2a598bad30e78.