GH action: instead disable haddock temporarily
8.4 gave:
Error: cabal: Failed to build documentation for vector-0.13.0.0 (which is
required by bugzilla-redhat-1.0.1).